# Generated by Django 5.0.4 on 2024-04-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='PostTag',
        ),
    ]
