# Generated by Django 5.0.4 on 2024-04-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_tag_posttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_advertised',
            field=models.BooleanField(default=False),
        ),
    ]
